package eu.kanade.tachiyomi.extension.id.pixhentai

import eu.kanade.tachiyomi.multisrc.oceanwp.OceanWP
import eu.kanade.tachiyomi.source.model.FilterList

class PixHentai : OceanWP("Pix Hentai", "https://pixhentai.com", "id") {

    override val filterParam: String = "genre"

    override fun getFilterList(): FilterList = FilterList(
        GenreFilter(),
    )

    private class GenreFilter : UriPartFilter(
        "Genre",
        arrayOf(
            Pair("All", ""),
            Pair("English Translated", "english-translated"),
            Pair("Komik Hentai Indonesia", "komik-hentai-indonesia"),
            Pair("Anal", "anal"),
            Pair("Anime", "anime"),
            Pair("Athlete", "athlete"),
            Pair("Beach", "beach"),
            Pair("Bedroom", "bedroom"),
            Pair("Big Boobs", "big-boobs"),
            Pair("Bikini", "bikini"),
            Pair("Blowjob", "blowjob"),
            Pair("Bondage", "bondage"),
            Pair("Breast Sucking", "breast-sucking"),
            Pair("Bukkake", "bukkake"),
            Pair("Cheating", "cheating"),
            Pair("Classroom", "classroom"),
            Pair("Consensual", "consensual"),
            Pair("Cosplay", "cosplay"),
            Pair("Cowgirl", "cowgirl"),
            Pair("Daughter", "daughter"),
            Pair("Doctor", "doctor"),
            Pair("Doggy", "doggy"),
            Pair("Double Penetration", "double-penetration"),
            Pair("Drama", "drama"),
            Pair("Festival", "festival"),
            Pair("Fingering", "fingering"),
            Pair("Footjob", "footjob"),
            Pair("Full Color", "full-color"),
            Pair("Girlfriend", "girlfriend"),
            Pair("Girls und Panzer", "girls-und-panzer"),
            Pair("Glasses", "glasses"),
            Pair("Groping", "groping"),
            Pair("Gundam Seed Destiny", "gundam-seed-destiny"),
            Pair("Handjob", "handjob"),
            Pair("Harem", "harem"),
            Pair("Hinata", "hinata"),
            Pair("Hospital", "hospital"),
            Pair("Hot pants", "hot-pants"),
            Pair("Hotel", "hotel"),
            Pair("Incest", "incest"),
            Pair("Kimono", "kimono"),
            Pair("Large Breasts", "large-breasts"),
            Pair("Lolicon", "lolicon"),
            Pair("Macross Frontier", "macross-frontier"),
            Pair("Missionary", "missionary"),
            Pair("Modern", "modern"),
            Pair("Mom", "mom"),
            Pair("Mother", "mother"),
            Pair("Naruto", "naruto"),
            Pair("Nurse", "nurse"),
            Pair("Office lady", "office-lady"),
            Pair("Outdoor", "outdoor"),
            Pair("Paizuri", "paizuri"),
            Pair("Pool", "pool"),
            Pair("Rape", "rape"),
            Pair("Restaurant", "restaurant"),
            Pair("Restroom", "restroom"),
            Pair("Romance", "romance"),
            Pair("Sakura", "sakura"),
            Pair("Small Breasts", "small-breasts"),
            Pair("Small Tits", "small-tits"),
            Pair("Step Mom", "step-mom"),
            Pair("Step Mother", "step-mother"),
            Pair("Step Sister", "step-sister"),
            Pair("Stockings", "stockings"),
            Pair("Student", "student"),
            Pair("Swimsuit", "swimsuit"),
            Pair("Teacher", "teacher"),
            Pair("Teenager", "teenager"),
            Pair("Threesome", "threesome"),
            Pair("Uncensored", "uncensored"),
            Pair("Uncle", "uncle"),
            Pair("Uniform", "uniform"),
            Pair("Vanilla", "vanilla"),
            Pair("Workmate", "workmate"),
        ),
    )
}
